### ISSUE TITLE
Support xonsh rc.d

### ISSUE THREAD

**Issue by rpdelaney** [xxh/xxh-shell-xonsh-appimage#20]
**Is your feature request related to a problem? Please describe.**
I use rc config pattern as you can see in [my dotfiles](https://github.com/rpdelaney/dotfiles/tree/main/home/.config/xonsh). xxh install does not copy it:

```console
$ xxh dickbag +s xonsh +if
Install xxh-shell-xonsh to dickbag:/home/ryan/.xxh
Remove dickbag:/home/ryan/.xxh/.xxh
First time upload using scp (this will be omitted on the next connections).
Note: you can install rsync on local and remote host to increase speed.
xonshrc.xsh                                                                                                                   100% 2039    53.9KB/s   00:00
xonsh                                                                                                                         100%   25MB   9.5MB/s   00:02
entrypoint.sh                                                                                                                 100% 3872   127.2KB/s   00:00
```

**Describe the solution you'd like**
`xxh +i` should bring everything in `~/.config/xonsh`.

**Describe alternatives you've considered**
I can do it manually, but that defeats the purpose of `xxh +i`.

**For community:**
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
Hi @rpdelaney!

xxh is based on some principles and one of these:

> Careful. No blindfold copying config files from local to remote host. Following privacy and repeatability practices the best way is to fork the xxh plugin or shell example and pack your configs into it. 

I recommend to use https://github.com/xxh/xxh-plugin-prerun-dotfiles to pack your dotfiles.
